# Usar imagem base Python 3.9
FROM python:3.9-slim

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivo carguru.py para o container
COPY carguru.py .

# Comando padrão ao iniciar o container
CMD ["python", "carguru.py"]
